name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: clang -o forth system.c execute.c macro.c core.c optional.c bootstrp.c main.c -ansi -Wall -pedantic

